### ISSUE TITLE
Images not Loading

### ISSUE THREAD

**Issue by Sid-2002** [2anki/server#928]

**Comment by aalemayhu** [comment]
Second-pass review (engineer): Relevant code exists but no fix commit found

Evidence: code in: web/src/pages/LandingPage/copy/quizlet.ts
web/src/pages/LandingPage/copy/notion.

**Comment by aalemayhu** [comment]
Maintainer deployed a filename fix at the time of the report (Jul 2022) and asked the reporter to confirm. The reporter's follow-up suggested it was a multi-device Anki sync issue rather than a 2anki.net generation bug. No code path currently produces broken image filenames for HTML-exported Notion pages. Closing as addressed.
